### ISSUE TITLE
Fail to get an item from dynamo table (parsing error?)

### ISSUE THREAD

**Issue by Jae** [jed/dynamo#4]
raw response from dynamoDB below fails when Attributes.prototype.parse(data)

{ 
  ConsumedCapacityUnits: 0.5,
  Item: 
  { 
    name: { S: 'Christian Lewis' },
    id: { S: '28664d40-6195-11e1-8d85-0be46e39396b' },
    screen_name: { S: 'Tyler Young' } 
  }
}

I'm suspecting it's to do with ConsumedCapacityUnits

Am I not supposed to do table.get(key).fetch(opts, cb)?

It's basically failing to parse the raw response from Dynamo with stacktrace below

TypeError: Object.keys called on non-object
      at Function.keys (native)
      at Object.parse (node_modules/dynamo/lib/Value.js:17:23)
      at node_modules/dynamo/lib/Attributes.js:20:34
      at Array.forEach (native)
      at Object.parse (node_modules/dynamo/lib/Attributes.js:18:23)
      at node_modules/dynamo/lib/Item.js:54:32
      at node_modules/dynamo/lib/Database.js:67:44
      at IncomingMessage.<anonymous> (node_modules/dynamo/lib/Request.js:38:43)

**Comment by jed** [comment]
that should do it, sorry that my tests hadn't extended to item yet. let me know if you're still having trouble.

**Comment by Jae** [comment]
should this handle the case of non existing item for the key?

dynamoDB doesn't seem to error for that.

**Comment by jed** [comment]
hmmm, not sure that would be an error, per se. amazon would just return an empty object, right?

**Comment by Jae** [comment]
it returns almost empty object like { ConsumedCapacityUnits: 0.5 } then the parsing fails because of Object.keys(undefined)

TypeError: Object.keys called on non-object
      at Function.keys (native)
      at Object.parse (/node_modules/dynamo/lib/Attributes.js:17:12)
      at /node_modules/dynamo/lib/Item.js:54:39
      at /node_modules/dynamo/lib/Database.js:67:44
      at IncomingMessage.<anonymous> (/node_modules/dynamo/lib/Request.js:38:43)
      at IncomingMessage.emit (events.js:88:20)
      at HTTPParser.onMessageComplete (http.js:137:23)
      at Socket.ondata (http.js:1147:24)
      at TCP.onread (net.js:354:27)
